

#ifndef INC_JUEGOSCARACTERES_JUEGOCARACTERES11X16_H_
#define INC_JUEGOSCARACTERES_JUEGOCARACTERES11X16_H_

#include <stdint.h>

extern const uint8_t juegoCaracteres11x16[];

#endif /* INC_JUEGOSCARACTERES_JUEGOCARACTERES11X16_H_ */
