

#ifndef INC_JUEGOSCARACTERES_SANSSERIF8X13AMARILLO_H_
#define INC_JUEGOSCARACTERES_SANSSERIF8X13AMARILLO_H_

#include <stdint.h>

extern const uint8_t SansSerif8x13Amarillo[];

#endif /* INC_JUEGOSCARACTERES_SANSSERIF8X13AMARILLO_H_ */
