

#ifndef INC_JUEGOSCARACTERES_CONSOLAS9X18AMARILLO_H_
#define INC_JUEGOSCARACTERES_CONSOLAS9X18AMARILLO_H_

#include <stdint.h>

extern const uint8_t Consolas9x18Amarillo[];

#endif /* INC_JUEGOSCARACTERES_CONSOLAS9X18AMARILLO_H_ */
