


#ifndef INC_JUEGOSCARACTERES_JUEGOCARACTERES8X11_H_
#define INC_JUEGOSCARACTERES_JUEGOCARACTERES8X11_H_

#include <stdint.h>

extern const uint8_t juegoCaracteres8x11[];

#endif /* INC_JUEGOSCARACTERES_JUEGOCARACTERES8X11_H_ */
